## Makefile.am -- Process this file with automake to produce Makefile.in

INCLUDES        = -I$(top_builddir)/common

noinst_LIBRARIES    = libjuken.a
libjuken_a_SOURCES  = serialdevice.cpp \
                      kenwooddevice.cpp \
                      kenwoodchanger.cpp \
                      util.cpp

#libjuken_a_LIBADD   = $(top_builddir)/common/libcommon.a
